[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# PostHog Analytics Proxy to avoid ad blockers
[[redirects]]
  from = "/analytics/*"
  to = "https://us.i.posthog.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/analytics-assets/*"
  to = "https://us-assets.i.posthog.com/:splat"  
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 5173